/** Super Townhouse — Application Routes */
export const ROUTES = {
  home: '/',
  rooms: '/rooms',
  room: (id: string) => `/rooms/${id}`,
  gallery: '/gallery',
  about: '/about',
  contact: '/contact',
  facilities: '/facilities',
  faq: '/faq',
  policies: '/policies',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',

  dashboard: '/dashboard',
  dashboardProfile: '/dashboard/profile',
  dashboardBookings: '/dashboard/bookings',
  dashboardNotifications: '/dashboard/notifications',

  admin: '/admin',
  adminDashboard: '/admin/dashboard',
  adminBookings: '/admin/bookings',
  adminCalendar: '/admin/calendar',
  adminRooms: '/admin/rooms',
  adminGallery: '/admin/gallery',
  adminReviews: '/admin/reviews',
  adminOffers: '/admin/offers',
  adminPayments: '/admin/payments',
  adminReports: '/admin/reports',
  adminSettings: '/admin/settings',
  adminCms: '/admin/cms',
  // Phase 8 — Analytics & Search
  adminSearch:          '/admin/search',
  adminAnalyticsBookings: '/admin/analytics/bookings',
  adminAnalyticsRooms:    '/admin/analytics/rooms',
  adminAnalyticsGuests:   '/admin/analytics/guests',
} as const;
